require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '13.0'  # use actual version instead of min_ios_version_supported

prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => :static 
end

config = use_native_modules!  # move here, outside target block

target 'SwedishLearningApp' do
  # config is already defined above, no need to define again

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'SwedishLearningAppTests' do
    inherit! :complete
  end
end

post_install do |installer|
  react_native_post_install(
    installer,
    config[:reactNativePath],  # now accessible here
    :mac_catalyst_enabled => false,
  )
  
  # (optional) force deployment target for all pods to 13.0 here if needed
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
